make test launch easier
oltodo/worldcup-for-slack pull request #2
Opened 2018-06-21 07:40 UTC by wulfy

Je ne sais pas comment les tests en dev étaient lancés mais une ptite commande Yarn me semblait plus facile

Lancer en mode DEV avec le match par défaut
```yarn test ``` 

Lancer en mode DEV avec le 3eme match
```yarn test 3``` 

Et si on met le match 5000 ça ne marche pas :)

2018-06-21 07:43 UTC, oltodo requested changes

2018-06-21 07:43 UTC, oltodo commented on package.json
> +    "test": "NODE_ENV=development babel-node src"
👎 C'est plutôt à toi de configurer ton environnement de travail en dev

2018-06-21 07:49 UTC, wulfy commented on package.json
> +    "test": "NODE_ENV=development babel-node src"
perso ca évite de mettre des variables d'environnement à chaque fois et lancer le bon match.
Mais ok au pire je fais ça que sur ma machine ;)

2018-06-21 08:09 UTC, oltodo commented on package.json
> +    "test": "NODE_ENV=development babel-node src"
Non mais quand tu développes, ton NODE_ENV doit toujours être en `development`. Donc pas besoin de le préciser.

2018-06-21 08:13 UTC, wulfy commented on package.json
> +    "test": "NODE_ENV=development babel-node src"
oui mais j'ai besoin par moments de lancer en mode "production" pour , par exemple, tester comment il récupère les données du vrai flux, comment il attend avant de crawl.

2018-06-21 08:16 UTC, oltodo commented on package.json
> +    "test": "NODE_ENV=development babel-node src"
Tu ne réécris jamais ta commande à chaque exécution. Ok pour rajouter un script mais dans ce cas ce serait plutôt `dev`. Et il faut rajouter un `NODE_ENV=production` à `start` car sinon, les commandes `start` et `dev` auraient le même comportement.

2018-06-21 09:48 UTC, wulfy commented on package.json
> +    "test": "NODE_ENV=development babel-node src"
d'acc je vais modifier

2018-06-21 20:12 UTC, wulfy commented
@oltodo mieux?

2018-06-22 06:03 UTC, oltodo approved these changes

2018-06-22 07:13 UTC, merged